docker-deploy/web-app/basicapp/urls.py
from django.urls import path
from django.contrib import admin
from django.urls import re_path
from . import views
app_name = "basicapp"
urlpatterns = [
    path('', views.CreateOrderView.as_view(), name="homepage"), 
    path('register/',views.RegisterView.as_view(),name = "register"), 
    path('login/',views.UserLoginView.as_view(),name = "login"),
    path('logout/',views.UserLogoutView.as_view(),name = "logout"), 
    path('success/',views.OrderSuccessView.as_view(),name = "ordersuccess"),
    re_path(r'^info/(?P<pk>\d+)/$',views.PersonalInfoView.as_view(),name = "personalinfo"), # personal info view
    re_path(r'^updateinfo/(?P<pk>\d+)/$',views.UpdateInfoView.as_view(),name = "updateinfo"), # update personal info view
    re_path(r'^myrides/(?P<pk>\d+)/$',views.UserOpenRidesView.as_view(),name = "rides"),# my rides view
    re_path(r'^todrive/(?P<pk>\d+)/$',views.ToDriveView.as_view(),name = "todrive"),# To drive view
    re_path(r'^driveconfirm/(?P<pk>\d+)/$',views.ConfirmDriveView.as_view(),name="confirmdrive"),# Driver confirm drive
    re_path(r'^joinshare/(?P<pk>\d+)/$',views.JoinShareView.as_view(),name="joinshare"), # all sharable orders suitable
    re_path(r'^joininfo/(?P<pk>\d+)/$',views.JoinInfoView.as_view(),name="editjoininfo"),# edit join share info
    re_path(r'^editopenride/(?P<pk>\d+)/$',views.EditOpenRideView.as_view(),name="editride"),# edit open ride info 
    re_path(r'^myrideinfo/(?P<pk>\d+)/$',views.RideDetailView.as_view(),name="rideinfo"), #view ride detail
    re_path(r'^myshareinfo/(?P<pk>\d+)/$',views.ShareDetailView.as_view(),name="sharerideinfo"), #view share detail
    re_path(r'^deleteride/(?P<pk>\d+)/$',views.RideDeleteView.as_view(),name="deleteride"), #delete open detail
    re_path(r'^deleteshare/(?P<pk>\d+)/$',views.ShareDeleteView.as_view(),name="deleteshare"), #delete share info
    re_path(r'^mydriveinfo/(?P<pk>\d+)/$',views.DriveDetailView.as_view(),name="driveinfo"), #view drive detail
    re_path(r'^completedrive/(?P<pk>\d+)/$',views.CompleteDriveView.as_view(),name="completedrive") #view drive detail
]

docker-deploy/web-app/project1/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('basicapp.urls')),
    path('admin', admin.site.urls),
]

docker-deploy/web-app/templates/base.html
{%load static%}

<html>
    
    <head>
        {%block title%}
        {%endblock%}
        <meta charset="utf-8">
       
        
        <!-- Bootstrap -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
        <!-- Medium editor -->
        <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
        <!-- static css -->
        <link rel="stylesheet" href="{%static 'basicapp.css'%}">
    </head>

    <body style='overflow-y:scroll;background-color:#123'>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color:grey;">
    
            <div class="container">
                <ul class="navbar-nav">
                    <li class="nav-item"><a style = 'color:white;'class=" navbar-brand" href="{%url 'basicapp:homepage'%}"> Home </a></li>
               
                    
                    {% if user.is_authenticated%}
                    <li class="nav-item"><a style = 'color:white;' class=' nav-link active' href="{% url 'basicapp:todrive' pk=user.pk %}"> ToDrive </a></li>
                    <li class="nav-item"><a style = 'color:white;' class='nav-link active' href="{% url 'basicapp:joinshare' pk=user.pk%}">JoinShare</a></li>
                    {%endif%}

                </ul>
               
                {% if user.is_authenticated%}
                    <ul class="navbar-nav navbar-right">
                 
                    <li class="nav-item"><a style = 'color:white;' class=' nav-link active' href="{%url 'basicapp:personalinfo' pk=user.pk%}">MyInfo</a></li>
                    <li class="nav-item"><form id ="logout-form" method = "post"> {%csrf_token%}<a style = 'color:white;' class=' nav-link active' href="{%url 'basicapp:logout'%}">Logout </a></form></li>
                    </ul>
                {%else%}
                    <ul class="navbar-nav navbar-right">
                    <li class="nav-item"><a style = 'color:white;'class=' nav-link active' href="{%url 'basicapp:register'%}">Register</a></li>
                    <li class="nav-item"><a style = 'color:white;'class=' nav-link active' href="{%url 'basicapp:login'%}">Login</a></li>
                    </ul>

                {%endif%}


                
            </div>


        </nav>

      
    
        {%block body_block%}

        {%endblock%}
        

    </body>



</html>

docker-deploy/web-app/templates/confirmdrive.html
{%extends './base.html'%}

{%block title%}
<title>success</title>
{%endblock%}

{%block body_block %}
<!DOCTYPE html>
<html>
   <head>
      <title>HTML Meta Tag</title>
      <meta http-equiv = "refresh" content = "3; url = / " />
   </head>
   <body>
    <br>
    <div class="container" align = "center">
      <button  class="btn btn-warning"><h1 style = "color:azure;font-size: x-large;">You have confirmed an order!</h1>
      </button>
    </div>
    </body>
</html>

{%endblock%}

docker-deploy/web-app/templates/deleteride.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>deleteride</title>

{%endblock%}

{%block body_block%}
<form action='{% url 'basicapp:deleteride' object.pk %}' method="post">{% csrf_token %}
    <p class = 'text-white'>Are you sure you want to delete "Ride #{{ object.ride_id }}"?</p>
    {{ form }}
    <input type="submit"  class="btn btn-info" value="Confirm">
    <a href="{% url 'basicapp:rides' pk=user.pk%}">
        <button type="button" class="btn btn-info">No</button>
    </a>
</form>
{%endblock%}

docker-deploy/web-app/templates/deleteshare.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>deleteshare</title>

{%endblock%}

{%block body_block%}
<form action='{% url 'basicapp:deleteshare' object.id %}' method="post">{% csrf_token %}
    <p class = 'text-white'>Are you sure you want to delete "Share #{{ object.id }}"?</p>
    {{ form }}
    <input type="submit"  class="btn btn-info" value="Confirm">
    <a href="{% url 'basicapp:rides' pk=user.pk%}">
        <button type="button" class="btn btn-info">No</button>
    </a>
</form>
{%endblock%}

docker-deploy/web-app/templates/editrides.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>EditRides</title>
{%endblock%}



{%block body_block%}

<form action='' method="post">
    {% csrf_token %}
    <p><br></p>
    {% for item in form %}
    <div class="container">
        <div class=" row col-6 mb-3">
            <label class="col-sm-3 text-white">{{ item.label_tag }}</label>
            <div class="col">
                {{ item }}
                {{ item.errors }}
            </div>
        </div>
    </div>
    {% endfor %}
    <div class="container">
        <p class="col-3"><button type="submit" class="btn btn-primary">save</button></p>
    </div>
</form>
{%endblock%}

docker-deploy/web-app/templates/homepage.html
{%extends './base.html'%}
{%load bootstrap4%}
{%block title%}
    <title>homepage</title>
{%endblock%}

{%block body_block%}
{%if user.is_authenticated%}
    <br>
    <br>
    <div class="container">
      
            <div class="col col-4">
                <h1 style="color:aliceblue">Go Somewhere!</h1>
           
            </div>
        </div>
       
    </div>
   
    
    <div class ="container text-center">
        <div class="row" >
            <!-- first half part -->
            {%csrf_token%}
            <div class="col col-sm-8">
                <form method = "POST">
                    {%csrf_token%}
                    <div style="color:aliceblue;font-size: x-large;" class="container-fluid"> {%bootstrap_form form%}</div>
                    <br>
                    <div align="center"> <input type="submit" class='btn btn-primary' style="background-color: lightblue; color:black" value="submit">
                    </div>
                   
                </form>
          
           
            </div>
            <!-- second half part  -->
            <div class = "col col-sm-4">
              
                <h1 style="color:aliceblue">Check My Orders!</h1>
                <br>
                <br>
                <a href="{% url 'basicapp:rides' pk=user.pk%}">
                    <button type="button" class="btn btn-info">MyOrders</button>
                </a>
                <br>
                <br>
                <br>
            </div>

        </div>

    </div>
{%else%}
    <div class='container' align="center"> 
        <br>
        <br>
        <br>
        <br>
         <h1 style="color:white" > WELCOME TO HOMEPAGE!</h1>
        <br>
        <br>
        <br>
        <h2 style="color:whitesmoke"> PLEASE LOG IN OR REGISTER FIRST!</h2>
    </div>
{%endif%}
{%endblock%}

docker-deploy/web-app/templates/login.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>Login</title>
{%endblock%}

{%block body_block%}
<br>
<div class="container" align="center">
    <h1 style="color:aliceblue"> Login Your Account Now!</h1>
</div>
<br>

<form method="POST">
    {%csrf_token%}
    <div style="color:aliceblue;font-size: x-large;" class="container-fluid"> {%bootstrap_form form%}</div>
    <br>
    <div align="center"> <input type="submit" class='btn btn-primary' style="background-color: lightblue; color:black"
            value="Login">
    </div>

</form>


{%endblock%}

docker-deploy/web-app/templates/ordersuccess.html
{%extends './base.html'%}

{%block title%}
<title>success</title>
{%endblock%}

{%block body_block %}
<!DOCTYPE html>
<html>
   <head>
      <title>HTML Meta Tag</title>
      <meta http-equiv = "refresh" content = "3; url = / " />
   </head>
   <body>
    <br>
    <div class="container" align = "center">
      <button type="button" class="btn btn-warning"><h1 style = "color:azure;font-size: x-large;">You have created an order!</h1>
      </button>
    </div>
    </body>
</html>

{%endblock%}

docker-deploy/web-app/templates/personalinfo.html
{%extends './base.html'%}


{%block title%}
    <title> Personal Info</title>
{%endblock%}


{%block body_block%}
    <div class="container-fluid" >
        <br>
        
        <br>
        <div class="row">
            <div class="col col-sm-3">
        

            </div>
            <div class="col col-sm-6">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">User ID:{{object.pk}}</li>
                    <li class="list-group-item">Account Email:{{object.email}}</li>
                    <li class="list-group-item">Name:{{object.name}}</li>
                    <li class="list-group-item">Is a registered Driver?  
                        {%if object.is_driver%} 
                            <button class="btn-info"> Yes</button>
                        {%else%}
                        <button class="btn-info"> No</button>
                        
                        {%endif%}
                    </li>
                    <li class="list-group-item">Vehicle Type:{{object.vehic_type}}</li>
                    <li class="list-group-item">License Number:{{object.lice_plate_number}} </li>
                    <li class="list-group-item"> Max Passenger Number:{{object.max_pass_num}}</li>
                  </ul>
                  


            </div>
            
            <div class="col col-sm-3">
                <br>
                <br>
                <br>
                <div class="container" algin="center"><a href="{%url 'basicapp:updateinfo' pk=object.pk %}"><button type='button' class="btn btn-warning">update</button></a></div>
            </div>
        </div>  
<br>
          
    </div>

   
{%endblock%}

docker-deploy/web-app/templates/rideinfo.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>rideinfo</title>
{%endblock%}
{%block body_block%}
<p><br></p>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <ul class="list-group">
                <li class="list-group-item active" aria-current="true">Ride {{ ride_list.0.ride_id }}</li>
                <li class="list-group-item">owner: {{ride_list.0.owner}}</li>
                <li class="list-group-item">dest_addr: {{ride_list.0.dest_addr}}</li>
                <li class="list-group-item">arr_date_time: {{ride_list.0.arr_date_time}}</li>
                <li class="list-group-item">party_num: {{ride_list.0.party_num}}</li>
                <li class="list-group-item">sharable: {% if ride_list.0.sharable %}yes{% else %}no{% endif %}</li>
                <li class="list-group-item">status: {{ride_list.0.status}}</li>
                {% if ride_list.0.status == 'cf' %}
                <li class="list-group-item">driver_acc: {{ride_list.0.driver_acc}}</li>
                <li class="list-group-item">required_vehic_type: {{ride_list.0.required_vehic_type}}</li>
                {% endif %}
                <li class="list-group-item">other_reg: {{ride_list.0.other_reg}}</li>
            </ul>
            <a href="{% url 'basicapp:rides' pk=user.pk%}">
                <button type="button" class="btn btn-info">Return to myorders</button>
            </a>
        </div>
        <div class="col-md-6">
            <div class="card border-success" style="width: 20rem;">
                <div style="width: 20rem;">
                    {% for sharers in ride_list %}
                    <div class="card-body bg-white">
                        <h5 class="card-title">Sharer: {{ sharers.name }}</h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><span class="badge bg-info text-white">sharer_party_num: {{sharers.share_party_num }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">email: {{sharers.email }}</span></li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

docker-deploy/web-app/templates/shareinfo.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>shareinfo</title>

{%endblock%}

{%block body_block%}
<p><br></p>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <div class="card border-success" style="width: 20rem;">
                <div style="width: 20rem;">
                    {% for ride in share_list %}
                    <div class="card-body bg-white">
                        <h5 class="card-title">Owner: </h5>
                        <h6>{{ ride.owner }}</h6>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><span class="badge bg-info text-white">owner_party_num: {{ ride.party_num }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">owner email: {{ ride.email }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">destination: {{ ride.dest_addr }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">arrival time: {{ ride.arr_date_time }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">status: {{ ride.status }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">your party number: {{ ride.share_party_num }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">driver: {{ ride.driver_acc.name }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">driver contact: {{ ride.driver_acc.email }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">driver plate number: {{ ride.driver_acc.lice_plate_number }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">driver vehicle: {{ ride.driver_acc.vehic_type }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">driver capacity: {{ ride.driver_acc.max_pass_num }}</span></li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card border-success" style="width: 20rem;">
                <div style="width: 20rem;">
                    {% for sharers in sharer_list %}
                    <div class="card-body bg-white">
                        <h5 class="card-title">Other Sharer{{forloop.counter}}: {{ sharers.name }}</h5>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item"><span class="badge bg-info text-white">sharer_party_num: {{ sharers.share_party_num }}</span></li>
                            <li class="list-group-item"><span class="badge bg-info text-white">email: {{ sharers.email }}</span></li>
                        </ul>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <a href="{% url 'basicapp:rides' pk=user.pk%}">
        <button type="button" class="btn btn-info">Return to myorders</button>
    </a>
</div>
{%endblock%}

docker-deploy/web-app/templates/todrive.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>ToDrive</title>
{%endblock%}
{%block body_block%}
{%if user.is_driver%}
<div class="container" >
    <br>
    {% for ride in open_ride_list %}
       
        {% if ride.status == 'op' %}
       
       
        <div class="row">
            <div class="col col-1">
               
            </div>
            <div class="col col-8">
                <ul class="list-group">
                    <li class="list-group-item active" aria-current="true">
                        Vehicle:{{ride.required_vehic_type}}
                        <div class="row">
                            <div class="col col-6">
                                OpenRide ID:{{ride.ride_id}} 
                            </div>
                            <div class="col col-6">
                                Owner:{{ride.owner}}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col col-6">
                                Sharable:{{ride.sharable}}
                            </div>
                            <div class="col col-6">
                                Party Number:{{ride.party_num}}
                            </div>
                        </div>
                       
                        <div class="row">
                            <div class="col col-6">
                                Destination: {{ride.dest_addr}}
                            </div>
                            <div class="col col-6">
                                Arrival at: {{ ride.arr_date_time }}
                            </div>
                        </div>
                        {% for share in all_shares %}
                            
                            {% if ride == share.share_id %}
                            <div class="row">
                                <div class="col col-6">
                                    Sharer ID: {{share.sharer_id}}
                                </div>
                                <div class="col col-6">
                                    Sharer Party Number: {{ share.share_party_num }}
                                </div>
                            </div>
                            {%endif%}
                        {%endfor%}
                        </li>
                </ul>
            </div>
            <div class="col col-3">
                <br>                       
                <a href="{% url 'basicapp:confirmdrive' pk=ride.pk %}"> 
                <button type="submit" class="btn btn-warning"><h1 style = "color:azure;font-size: x-large;">Confirm!</h1>
                </button>
                </a>
            
            </div>
            
        </div>

        <br>

        {%endif%}
    {%endfor%}
{%else%}
<html>
    
    <meta http-equiv = "refresh" content = "3; url = / " />
     <br>
     <div class="container" align = "center">
       <button type="button" class="btn btn-warning"><h1 style = "color:azure;font-size: x-large;">You are not a registered driver. Go update in 'Myinfo'. Return in 3 seconds.</h1>
       </button>
     </div>
 </html>

{%endif%}
</div>


{%endblock%}

docker-deploy/web-app/templates/updateinfo.html
{%extends './base.html'%}

{%load bootstrap4%}
{%block title%}
    <title> Update Info</title>
{%endblock%}


{%block body_block%}
    <div class="container-fluid" >
        <form method="post">{% csrf_token %}
        
            <div class="container-fluid" align="center">  <h1 style="color:aliceblue;font-size:x-large;">{{form.as_p}}</h1>
                <input type="submit" value="Update">
            </div>
            
    
        </form>
        
        
    </div>


{%endblock%}

docker-deploy/web-app/templates/userrides.html
{%extends "./base.html"%}
{%load bootstrap4%}
{%block title%}
<title>MyRides</title>

{%endblock%}

{%block body_block%}

<p><br></p>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="container">
                <h5 style="color:blanchedalmond">Your Rides</h5>
                <div class="card border-success" style="width: 20rem;">
                    <div style="width: 20rem;">
                        {% for object in open_ride_list %}
                        {% if object.status != "cp" %}
                        <div class="card-body bg-white">
                            <h5 class="card-title">YourRide ID: {{ object.ride_id }}</h5>
                            <p class="card-text">
                                {% if object.status == "op" %}
                                <span class="badge bg-success text-white">open</span>
                                {% else %}
                                <span class="badge bg-warning text-white">confirmed</span>
                                {% endif %}
                            </p>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><span class="badge bg-info text-white">destination: {{object.dest_addr }}</span></li>
                                <li class="list-group-item"><span class="badge bg-info text-white">arrivaltime: {{object.arr_date_time }}</span></li>
                                <li class="list-group-item"><span class="badge bg-info text-white">partynumber: {{object.party_num }}</span></li>
                            </ul>
                            {% if object.status == "op" %}
                            <a href="{%url 'basicapp:editride' pk=object.pk %}" class="card-link">edit</a>
                            <a href="{%url 'basicapp:deleteride' pk=object.pk %}" class="card-link">delete</a>
                            {% endif %}
                            <a href="{%url 'basicapp:rideinfo' pk=object.ride_id %}" class="card-link">details</a>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="container">
                <h5 style="color:blanchedalmond">Your Shares</h5>
                <div class="card border-success" style="width: 20rem;">
                    <div style="width: 20rem;">
                        {% for object in share_ride_list %}
                        {% if object.status != "cp" %}
                        <div class="card-body bg-white">
                            <h5 class="card-title">ShareRide ID: {{ object.ride_id }}</h5>
                            <p class="card-text">
                                {% if object.status == "op" %}
                                <span class="badge bg-success text-white">open</span>
                                {% else %}
                                <span class="badge bg-warning text-white">confirmed</span>
                                {% endif %}
                            </p>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><span class="badge bg-info text-white">owner: {{object.email }}</span></li>
                                <li class="list-group-item"><span class="badge bg-info text-white">ownerpartynumber: {{object.party_num }}</span></li>
                                <li class="list-group-item"><span class="badge bg-info text-white">mypartynumber: {{object.share_party_num }}</span></li>
                                <li class="list-group-item"><span class="badge bg-info text-white">destination: {{object.dest_addr }}</span></li>
                            </ul>
                            {% if object.status == "op" %}
                            <a href="{%url 'basicapp:deleteshare' pk=object.id %}" class="card-link">cancel</a>
                            {% endif %}
                            <a href="{%url 'basicapp:sharerideinfo' pk=object.ride_id %}" class="card-link">details</a>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-4">
            <div class="container">
                <h5 style="color:blanchedalmond">Your Drives</h5>
                <div class="card border-success" style="width: 20rem;">
                    <div style="width: 20rem;">
                        {% if is_driver %}
                        {% if drive_ride_list %}
                        {% for object in drive_ride_list %}
                        {% if object.status == 'cf' %}
                        <div class="card-body bg-white">
                            <h5 class="card-title">DriveRide ID: {{ object.ride_id }}</h5>
                            <p class="card-text">
                                <span class="badge bg-info text-white">{{ object.arr_date_time }}</span>
                            </p>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item"><span class="badge bg-info text-white">destination: {{ object.dest_addr }}</span></li>
                                <li class="list-group-item"><span class="badge bg-info text-white">owner: {{ object.owner }}</span></li>
                            </ul>
                            <a href="{% url 'basicapp:driveinfo' pk=object.ride_id %}" class="card-link">details</a>
                            <a href="{% url 'basicapp:completedrive' pk=object.ride_id %}" class="card-link">complete</a>
                        </div>
                        {% endif %}
                        {% endfor %}
                        {% else %}
                        <h5 class="card-title">You don't have a drive order!</h5>
                        <a href="{% url 'basicapp:todrive' pk=user.pk %}">
                            <button type="button" class="btn btn-info">Claim a drive!</button>
                        </a>
                        {% endif %}
                        {% else %}
                        <h5 class="card-title">You are not a driver!</h5>
                        <a href="{%url 'basicapp:updateinfo' pk=user.pk %}">
                            <button type="button" class="btn btn-info">Be a driver!</button>
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}